import Navbar from "@/components/navbar/Navbar";
import "./globals.css";


export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container mx-auto h-[calc(100vh-9rem)] flex justify-center items-center">
          {children}
        </main>
      </body>
    </html>
  );
}
